refactored icon links
devosu/dev-website pull request #9
Opened 2024-07-08 01:37 UTC by GulkoA

I refactored and renamed iconTextLink shortcode to easily add outlinks with icons. This is useful for the team page, I included an example of that with @KemingHe 's github

2024-07-08 20:30 UTC, KemingHe requested changes
Please see comment for the `static/css/style.css` paired with the bug screenshot for changes needed.

2024-07-08 20:30 UTC, KemingHe commented on content/team.md
@GulkoA 

I found an unexpected formatting bug in the latest build when running `hugo server` locally (screenshot attached).

This is likely caused by the new CSS rule added. Please investigate further.

On the bright side, the link works fine though. ☀️ 

![Screenshot from 2024-07-08 16-06-54](https://github.com/devosu/dev-website/assets/44534763/41379438-b1ee-4853-86c8-502bb6c7d270)

2024-07-08 20:30 UTC, KemingHe commented on static/css/style.css
# Investigation Sofar

The CSS code snippet for the `.inline-icon` class can cause layout issues, such as a large gap in the rendered webpage, due to several potential factors. Here's a detailed analysis of each property and how it might contribute to the issue:

1. **`max-height: 1rem;` and `max-width: 1.1rem;`**:
   - **Issue**: If the actual size of the icon exceeds these maximum dimensions, the icon will be scaled down to fit within these limits. This can sometimes cause unexpected rendering behavior, especially if the container expects a larger element.
   - **Potential Gap**: If the container or surrounding elements are designed based on the icon's natural size, scaling it down might create gaps where the larger icon was expected to fit.

2. **`margin: 0 0.4rem 0 0;`**:
   - **Issue**: This sets a right margin of `0.4rem`, which adds extra space to the right of the icon. If multiple icons or elements with this class are used in a row, the cumulative effect of this margin could result in significant spacing.
   - **Potential Gap**: The right margin can cause gaps between icons or between the icon and the following text or element, potentially leading to a disjointed appearance.

3. **`vertical-align: baseline;`**:
   - **Issue**: Aligning the icon to the baseline can sometimes cause vertical misalignment issues, especially if the surrounding text or elements have different vertical alignment settings.
   - **Potential Gap**: This property might cause the icon to not align properly with the text, leading to vertical gaps or uneven spacing, which can be more pronounced if the text line height is different from the icon height.

2024-07-18 23:01 UTC, GulkoA commented
Keming, I wasn't able to recreate the issue on the screenshot in chromium or firefox, looks like the CSS didn't properly load when you started local server. I did replace all logo files with a pre-downscaled png, which should resolve the issue. I also slightly adjusted the CSS to impose a 16px height limit, which should bound anyone who didn't predownscale a png. The margin is important to have a gap between an icon and text. The text is by default baseline aligned and should not be changed, so the icon will be aligned properly.

2024-07-19 20:16 UTC, KemingHe requested changes, later dismissed
# Keming's Review

## On Style Fix

Awesome fix, @GulkoA , hopefully you found my investigation helpful during the refactor.

## On New Look

Personal opinion: the new styling works but <ins>creates clutter</ins> when implemented at scale. Especially on mobile devices.

### On iPhone 11 Pro

Case 1: official mobile ratio, all links

![Screenshot from 2024-07-19 15-55-16](https://github.com/user-attachments/assets/15b0cdb3-be2c-4fca-99d1-0e31096bacf0)

### On Browser

Case 1: all links

![Screenshot from 2024-07-19 15-57-42](https://github.com/user-attachments/assets/c4e0f1a4-0800-4d8c-9265-5f91e1bbbbe4)

Case 2: some links

![Screenshot from 2024-07-19 16-08-56](https://github.com/user-attachments/assets/1ed8bb15-29a3-423c-8a8b-6af0d58fc020)


Case 3: very few links

![Screenshot from 2024-07-19 16-10-40](https://github.com/user-attachments/assets/ff16ed4f-0fb1-4bb7-8b8f-20324a0cf3e1)

## Proposed Changes

Choose one or many of the following:

- [ ] Add alignment either hard-code or through md table or through 3rd party lib for hugo.
- [ ] Make links only appear when hovering on name; thus avoiding clutter AND conflict with current styling.
- [ ] Use trailing icons instead of icons with text as links, this has the same issue of visual clutter once mass applied and is not recommended unless for a quick fix.

![Screenshot from 2024-07-19 16-15-06](https://github.com/user-attachments/assets/18d15efa-dc07-42e3-b2d7-c4efad9857be)

2024-07-19 20:20 UTC, KemingHe commented
- [ ] Maybe a darker background will work? I'll add that as a suggestion and let you decide. (Def not `background-color: black;` 🤣 )

![Screenshot from 2024-07-19 16-18-15](https://github.com/user-attachments/assets/a4b98cca-b1e3-42d5-97b5-bc597bc91b50)

2024-08-08 02:44 UTC, GulkoA commented
@KemingHe I changed the style to icons only here, I think it looks clean:
![image](https://github.com/user-attachments/assets/5c105065-bd3f-4cd6-ab7b-b117a1e41d13)

2024-08-25 15:31 UTC, merged